# Generated by Django 3.1.5 on 2021-01-04 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='desciption',
            field=models.TextField(default='123', max_length=500),
        ),
        migrations.AddField(
            model_name='task',
            name='solution',
            field=models.FloatField(default=123),
        ),
    ]
