# Generated by Django 3.1.5 on 2021-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210107_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='data',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
