# Generated by Django 3.1.5 on 2021-02-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_task_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='solution',
            field=models.TextField(default='123', max_length=500),
        ),
    ]
